Build does not fail anymore, when some service isn't reachable
AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin pull request #3
Opened 2022-01-20 19:28 UTC by oniboni

Improvements:
* Build does not fail anymore, when some service isn't reachable
* In case of fail: adds error admonition + code fence
* Added logging
* UMLet added

2022-01-21 16:02 UTC, b-bittner commented on kroki/plugin.py
> +
Please remove those spaces in line 117

2022-01-21 16:04 UTC, b-bittner requested changes
This PR looks great, please remove the spaces at line 117 and also add the underscore (_) in function "on_page_markdown" on line 133, so it is the same as in the other ones.

2022-01-21 16:06 UTC, fuzzy-focus requested changes
To be more precise:

`def on_page_markdown(self, markdown, files, page, **kwargs):`
should be
`def on_page_markdown(self, markdown, files, page, **_kwargs):`
for consistency with the rest of the modifications.

2022-01-25 09:31 UTC, oniboni commented on kroki/plugin.py
> +
```suggestion

```

2022-01-25 12:59 UTC, fuzzy-focus approved these changes
👍

2022-01-27 12:17 UTC, b-bittner approved these changes
Looks fantastic, ready for merge...

2022-01-27 12:18 UTC, merged